######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 10 21:24:22 2008
######################################################################

TEMPLATE = app
TARGET = items
DEPENDPATH += . release
INCLUDEPATH += .

# Input
HEADERS += graphicsitem.h mainwidget.h
SOURCES += graphicsitem.cpp main.cpp mainwidget.cpp
RESOURCES += graphicsitem.qrc
