######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 10 19:40:21 2008
######################################################################

TEMPLATE = app
TARGET = drawer
DEPENDPATH += . release
INCLUDEPATH += .

# Input
HEADERS += drawer.h
SOURCES += drawer.cpp main.cpp
RESOURCES += drawer.qrc
TRANSLATIONS += drawer_zh.ts
