######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 26 10:19:00 2008
######################################################################

TEMPLATE = app
TARGET = httpclient
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += httpclient.h
SOURCES += httpclient.cpp main.cpp
TRANSLATIONS += httpclient_zh.ts
QT += network
