######################################################################
# Automatically generated by qmake (2.01a) ??? ?? 12 15:37:15 2008
######################################################################

TEMPLATE = app
TARGET = splash
DEPENDPATH += .
INCLUDEPATH += .

QT += widgets 
CONFIG += c++11
# Input
HEADERS += mainwindow.h
SOURCES += main.cpp mainwindow.cpp
RESOURCES += splash.qrc
