######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 10 23:18:19 2008
######################################################################

TEMPLATE = app
TARGET = stack
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += stack.h
SOURCES += main.cpp stack.cpp
TRANSLATIONS += stack_zh.ts
