######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 10 22:21:39 2008
######################################################################

TEMPLATE = app
TARGET = pictrans
DEPENDPATH += . release
INCLUDEPATH += .

# Input
HEADERS += pictrans.h
SOURCES += main.cpp pictrans.cpp
RESOURCES += pictrans.qrc
