######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 10 19:41:22 2008
######################################################################

TEMPLATE = app
TARGET = eventfilter
DEPENDPATH += . release
INCLUDEPATH += .

# Input
HEADERS += eventfilter.h
SOURCES += eventfilter.cpp main.cpp
RESOURCES += eventfilter.qrc
TRANSLATIONS += eventfilter_zh.ts
