######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 10 21:37:38 2008
######################################################################

TEMPLATE = app
TARGET = itemtransform
DEPENDPATH += . release
INCLUDEPATH += .

QT += widgets
# Input
HEADERS += items.h mainwidget.h
SOURCES += items.cpp main.cpp mainwidget.cpp
RESOURCES += itemtransform.qrc
