######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 10 18:55:04 2008
######################################################################

TEMPLATE = app
TARGET = combine
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += baseinfo.h contact.h content.h detail.h
SOURCES += baseinfo.cpp contact.cpp content.cpp detail.cpp main.cpp
RESOURCES += combine.qrc
TRANSLATIONS += combine_zh.ts
