######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 10 19:51:15 2008
######################################################################

TEMPLATE = app
TARGET = gradient
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwidget.h paintarea.h
SOURCES += main.cpp mainwidget.cpp paintarea.cpp
TRANSLATIONS += gradient_zh.ts
