######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 10 19:08:04 2008
######################################################################

TEMPLATE = app
TARGET = delegate
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += combodelegate.h datedelegate.h spindelegate.h
SOURCES += combodelegate.cpp datedelegate.cpp main.cpp spindelegate.cpp
TRANSLATIONS += delegate_zh.ts
