######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 10 19:25:09 2008
######################################################################

TEMPLATE = app
TARGET = dir
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
