######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 10 19:47:37 2008
######################################################################

TEMPLATE = app
TARGET = fonts
DEPENDPATH += . release
INCLUDEPATH += .

# Input
HEADERS += fontset.h
SOURCES += fontset.cpp main.cpp
RESOURCES += fontset.qrc
TRANSLATIONS += fonts_zh.ts
