######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 10 19:44:29 2008
######################################################################

TEMPLATE = app
TARGET = fileinfomation
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += fileinformation.h
SOURCES += fileinformation.cpp main.cpp
TRANSLATIONS += fileinformation_zh.ts
