######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 10 19:50:01 2008
######################################################################

TEMPLATE = app
TARGET = geometry
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += geometry.h
SOURCES += geometry.cpp main.cpp
TRANSLATIONS += geometry_zh.ts
