######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 10 19:42:17 2008
######################################################################

TEMPLATE = app
TARGET = extension
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += extension.h
SOURCES += extension.cpp main.cpp
TRANSLATIONS += extension_zh.ts
