######################################################################
# Automatically generated by qmake (2.01a) ??? ?? 10 23:20:10 2008
######################################################################

TEMPLATE = app
TARGET = svg
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h svgwidget.h svgwindow.h
SOURCES += main.cpp mainwindow.cpp svgwidget.cpp svgwindow.cpp
TRANSLATIONS += svg_zh.ts
QT += svg
