######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 10 22:22:46 2008
######################################################################

TEMPLATE = app
TARGET = printimage
DEPENDPATH += . release
INCLUDEPATH += .

# Input
HEADERS += printimage.h
SOURCES += main.cpp printimage.cpp
RESOURCES += printimage.qrc
TRANSLATIONS += printimage_zh.ts
