######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 10 22:14:55 2008
######################################################################

TEMPLATE = app
TARGET = painterpath
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwidget.h paintarea.h
SOURCES += main.cpp mainwidget.cpp paintarea.cpp
TRANSLATIONS += painterpath_zh.ts
