######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 10 19:27:41 2008
######################################################################

TEMPLATE = app
TARGET = dockwindows
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += dockwindows.h
SOURCES += dockwindows.cpp main.cpp
TRANSLATIONS += dockwindows_zh.ts
