######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 7 08:49:39 2008
######################################################################

TEMPLATE = app
TARGET = designers
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mywidget.h
FORMS += first.ui second.ui third.ui
SOURCES += main.cpp mywidget.cpp
