######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 7 10:45:59 2008
######################################################################

TEMPLATE = app
TARGET = uiloader
INCLUDEPATH += .

CONFIG += uitools

# Input
HEADERS += mywidget.h
FORMS += first.ui second.ui 
SOURCES += main.cpp mywidget.cpp
RESOURCES += uiloader.qrc
