######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 10 23:29:09 2008
######################################################################

TEMPLATE = app
TARGET = table
DEPENDPATH += . release
INCLUDEPATH += .

# Input
HEADERS += table.h
SOURCES += main.cpp table.cpp
RESOURCES += table.qrc
TRANSLATIONS += table_zh.ts
