######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 10 22:13:31 2008
######################################################################

TEMPLATE = app
TARGET = painter
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += drawwidget.h painter.h
SOURCES += drawwidget.cpp main.cpp painter.cpp
TRANSLATIONS += painter_zh.ts
QT += core gui widgets
