######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 9 17:58:11 2008
######################################################################

TEMPLATE = app
TARGET = butterfly
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += butterfly.h
SOURCES += butterfly.cpp main.cpp
RESOURCES += butterfly.qrc
