######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 10 21:43:49 2008
######################################################################

TEMPLATE = app
TARGET = layoutdlg
DEPENDPATH += . release
INCLUDEPATH += .

# Input
HEADERS += layoutdlg.h
SOURCES += layoutdlg.cpp main.cpp
RESOURCES += layoutdlg.qrc
TRANSLATIONS += layoutdlg_zh.ts
