######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 10 23:17:21 2008
######################################################################

TEMPLATE = app
TARGET = splitter
DEPENDPATH += .
INCLUDEPATH += .

QT += widgets
# Input
SOURCES += main.cpp
TRANSLATIONS += splitter_zh.ts
