######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 10 21:45:01 2008
######################################################################

TEMPLATE = app
TARGET = listalign
DEPENDPATH += . release
INCLUDEPATH += .

# Input
HEADERS += listalign.h
SOURCES += listalign.cpp main.cpp
RESOURCES += listalign.qrc
TRANSLATIONS += listalign_zh.ts
