######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 10 19:03:31 2008
######################################################################

TEMPLATE = app
TARGET = datastream
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += pararw.h
SOURCES += main.cpp pararw.cpp
TRANSLATIONS += datastream_zh.ts
