######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 10 21:23:15 2008
######################################################################

TEMPLATE = app
TARGET = inputdialog
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += inputdialog.h
SOURCES += inputdialog.cpp main.cpp
RESOURCES += inputdialog.qrc
TRANSLATIONS += inputdialog_zh.ts
