######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 10 22:23:48 2008
######################################################################

TEMPLATE = app
TARGET = printtext
DEPENDPATH += . release
INCLUDEPATH += .

# Input
HEADERS += printtext.h
SOURCES += main.cpp printtext.cpp
RESOURCES += printtext.qrc
TRANSLATIONS += printtext_zh.ts
