######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 10 23:14:44 2008
######################################################################

TEMPLATE = app
TARGET = shapewidget
DEPENDPATH += . release
INCLUDEPATH += .

# Input
HEADERS += shapewidget.h
SOURCES += main.cpp qrc_test.cpp shapewidget.cpp
RESOURCES += shapewidget.qrc
