######################################################################
# Automatically generated by qmake (2.01a) ??? ?? 10 19:43:05 2008
######################################################################

TEMPLATE = app
TARGET = ftpclient
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ftpclient.h
SOURCES += ftpclient.cpp main.cpp
TRANSLATIONS += ftpclient_zh.ts
QT += network
