######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 10 19:38:43 2008
######################################################################

TEMPLATE = app
TARGET = dragtext
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += draglabel.h dragwidget.h
SOURCES += draglabel.cpp dragwidget.cpp main.cpp
