######################################################################
# Automatically generated by qmake (2.01a) ??? ?? 10 21:55:52 2008
######################################################################

TEMPLATE = app
TARGET = model
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h stringlistmodel.h
SOURCES += main.cpp mainwindow.cpp stringlistmodel.cpp
TRANSLATIONS += model_zh.ts
