######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 10 23:20:49 2008
######################################################################

TEMPLATE = app
TARGET = stringcodec
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += stringcodec.h
SOURCES += main.cpp stringcodec.cpp
TRANSLATIONS += stringcodec_zh.ts
