######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 10 21:38:50 2008
######################################################################

TEMPLATE = app
TARGET = keyevent
DEPENDPATH += . release
INCLUDEPATH += .

# Input
HEADERS += keyevent.h
SOURCES += keyevent.cpp main.cpp
RESOURCES += keyevent.qrc
TRANSLATIONS += keyevent_zh.ts
