######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 10 23:13:13 2008
######################################################################

TEMPLATE = app
TARGET = settings
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += settings.h
SOURCES += main.cpp settings.cpp
