######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 10 22:16:17 2008
######################################################################

TEMPLATE = app
TARGET = painttrans
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwidget.h paintarea.h
SOURCES += main.cpp mainwidget.cpp paintarea.cpp
TRANSLATIONS += painttrans_zh.ts
