######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 10 19:53:49 2008
######################################################################

TEMPLATE = app
TARGET = imgprocessor
DEPENDPATH += . release
INCLUDEPATH += .

# Input
HEADERS += imgprocessor.h
SOURCES += imgprocessor.cpp main.cpp
RESOURCES += imgprocessor.qrc
TRANSLATIONS += imgprocessor_zh.ts
