######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 10 21:58:11 2008
######################################################################

TEMPLATE = app
TARGET = messageboxs
DEPENDPATH += . release
INCLUDEPATH += .

# Input
HEADERS += messagebox.h
SOURCES += main.cpp messagebox.cpp
RESOURCES += messagebox.qrc
TRANSLATIONS += messagebox_zh.ts
