######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 10 23:32:21 2008
######################################################################

TEMPLATE = app
TARGET = view
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += histogramview.h mainwindow.h
SOURCES += histogramview.cpp main.cpp mainwindow.cpp
TRANSLATIONS += histogramview_zh.ts view_zh.ts
