######################################################################
# Automatically generated by qmake (2.01a) ??? ?? 12 16:27:22 2008
######################################################################

TEMPLATE = app
TARGET = progress
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += progress.h
SOURCES += main.cpp progress.cpp
TRANSLATIONS += progress_zh.ts
CONFIG += qtestlib
