######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 10 23:19:34 2008
######################################################################

TEMPLATE = app
TARGET = standarddialogs
DEPENDPATH += .
INCLUDEPATH += .

QT += widgets
# Input
HEADERS += standarddialogs.h
SOURCES += main.cpp standarddialogs.cpp
TRANSLATIONS += standarddialogs_zh.ts
