######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 10 22:03:40 2008
######################################################################

TEMPLATE = app
TARGET = mouseevent
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mouseevent.h
SOURCES += main.cpp mouseevent.cpp
TRANSLATIONS += mouseevent_zh.ts
