######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 10 23:30:53 2008
######################################################################

TEMPLATE = app
TARGET = toolbar
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += toolbar.h
SOURCES += main.cpp toolbar.cpp
TRANSLATIONS += toolbar_zh.ts
