######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 12 15:34:29 2008
######################################################################

TEMPLATE = app
TARGET = mapwidget
DEPENDPATH += . release
INCLUDEPATH += .

# Input
HEADERS += mapwidget.h
SOURCES += main.cpp mapwidget.cpp
RESOURCES += mapwidget.qrc
TRANSLATIONS += mapwidget_zh.ts
