######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 10 19:17:08 2008
######################################################################

TEMPLATE = app
TARGET = designer
DEPENDPATH += .
INCLUDEPATH += .

# Input
FORMS += name.ui
SOURCES += main.cpp
