######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 10 22:20:08 2008
######################################################################

TEMPLATE = app
TARGET = palette
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += palette.h
SOURCES += main.cpp palette.cpp
TRANSLATIONS += palette_zh.ts
