######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 10 19:37:12 2008
######################################################################

TEMPLATE = app
TARGET = dragicon
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += dragicon.h dragwidget.h
SOURCES += dragicon.cpp dragwidget.cpp main.cpp
RESOURCES += dragicon.qrc
