######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 10 23:33:54 2008
######################################################################

TEMPLATE = app
TARGET = workspace
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h
SOURCES += main.cpp mainwindow.cpp
TRANSLATIONS += workspace_zh.ts
